create or replace TYPE XXDMA_PO_SPEND_TAB
           IS TABLE OF XXDMA_PO_SPEND_OBJ;

create or replace TYPE "XXDMA_PO_SPEND_OBJ" AS OBJECT
(
        SPENDVALUE         NUMBER,
        SPENDCATEGORY      VARCHAR2(100),
        SPEND_PERIOD_FROM  VARCHAR2(100),
        SPEND_PERIOD_TO    VARCHAR2(100),
        OPERATING_UNIT     VARCHAR2(100)
);